### ISSUE TITLE
SocketStream has rendering issues

### ISSUE THREAD

**Issue by passy** [tastejs/todomvc#1019]
![screenshot 2014-10-08 16 22 57](https://cloud.githubusercontent.com/assets/9906/4561703/0c53ed6a-4eff-11e4-8242-9da5954fd37c.png)

Seen in Chrome Stable. Doesn't appear in Firefox, where we use the native checkboxes. Does anyone else see this as well?

**Comment by samccone** [comment]
:+1: still seeing this issue

**Comment by arthurvr** [comment]
Is it just for me or was this fixed in canary?
![socketstream_ _todomvc_and_socketstream_ _todomvc](https://cloud.githubusercontent.com/assets/6025224/6651695/c3f4cdd8-ca4f-11e4-80e4-4d87fe80ef39.png)

**Comment by passy** [comment]
It's super weird. I still see the encoding error in like 70% of the cases if I keep reloading the page.

**Comment by sindresorhus** [comment]
Doesn't matter though. We'll soon be moving it to the new template anyways.

**Comment by addyosmani** [comment]
Thanks so much for this contribution. I'm going through old issues and closing them out as we last updated the project in a major way in 2024 and want to ensure we're focused on only those issues still relevant. Thanks once again, feel free to reopen if still relevant
